---
# Source: microservice/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-microservice
  annotations:
    # The rollme makes the Secret resource be recreated every deploy. Hence the values from vault could be synced.
    rollme: "50VqV7zMKcUsAwkcFojIL5artduiDL0R"
type: Opaque
stringData:
