apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jsonnet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:sebastianusk/argocds.git
    targetRevision: HEAD
    path: jsonnet
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jsonnet
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
