apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: method1
  namespace: argocd
spec:
  project: default
  sources:
    - chart: echo-server
      repoURL: https://kubernetes-charts.banzaicloud.com
      targetRevision: 0.0.1
      helm:
        releaseName: method1
        valueFiles:
          - $values/method1/base/values.yaml
          - $values/method1/cluster/values.yaml
    - repoURL: git@github.com:sebastianusk/argocds.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
