---
# Source: echo-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo

    app.kubernetes.io/name: echo-server
    helm.sh/chart: echo-server-0.0.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: echo-server
  namespace: argocd
spec:
  ports:
    - name: tcp
      port: 80
      targetPort: 8080
  selector:
    app: echo
  type: LoadBalancer
---
# Source: echo-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: argocd
  labels:
    app: echo
    version: v1

    app.kubernetes.io/name: echo-server
    helm.sh/chart: echo-server-0.0.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo
        version: v1
    spec:
      containers:
        - name: echo
          image: "waynz0r/echo-server:master"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: IDENTIFIER
              value: "base"
          resources:
            limits:
              cpu: 1500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 64Mi
