apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: infra-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: clusters/config/infra/argocd/infra-apps/clustername
    repoURL: git@github.com:payfazz/nom-nom.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
