apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datadog
generators:
  - datadog.yaml
# helmCharts:
# - name: datadog
# repo: https://helm.datadoghq.com
# version: 3.6.7
# releaseName: datadog
# namespace: datadog
# valuesFile: values.yaml
# includeCRDs: true
