apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-appset
spec:
  generators:
    - git:
        repoURL: git@github.com:sebastianusk/argocds.git
        revision: master
        directories:
          - path: "clusters/config/infra/global/*"
  template:
    metadata:
      name: "global-appset-{{path.basename}}"
    spec:
      project: infra
      source:
        repoURL: git@github.com:sebastianusk/argocds.git
        targetRevision: master
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
