apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jsonnet
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/sebastianusk/argocds.git
        revision: HEAD
        directories:
          - path: deployment-jsonnet/values/*
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/sebastianusk/argocds.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: infra
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
